spring.application.name=finanzas-backend

# 1. Conectar a H2 en memoria
spring.datasource.url=jdbc:h2:mem:finanzasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Evitar que Hibernate y tu schema.sql se peleen
# 'none' significa: "Hibernate, no crees las tablas, ya las creo yo con mi schema.sql"
spring.jpa.hibernate.ddl-auto=none

# 3. La clave: Esperar a que las tablas existan para meter los datos
spring.jpa.defer-datasource-initialization=true

# 4. Ver qué está pasando en la consola
spring.jpa.show-sql=true